cave_explorer:
  max_radius: 20.0
  min_radius: 3.0
  sampling_angle_deg: 10
  max_sampling_angle_deg: 50
  max_planning_distance: 55.0

exploration_manager:
  min_distance: 30
  min_distance_visited: 10.0
  skip_for_loop_detection: 10

state_machine:
  time_between_states_s: 2
  min_dis_waypoint_back: 5.0
  max_dis_close_to_goal: 1.0
  max_speed_in_cave: 5.0

takeoff:
  - [-38.06, 10.0, 17.5, 3.2, -1.0, -1.0]
  - [-38.06, 10.0, 30.0, 3.2, -1.0, -1.0]

flyToCave:
  - [-150.0, 9.0, 30.0, 3.2, -1.0, -1.0]
  - [-200.2, 8.0, 25.0, 3.0, -1, -1]
  - [-322.0, 7.0, 20, 3.0, -1, -1]

trajectory_planner:
  dynamic_params:
    max_v: 30.0
    max_a: 1.0
