junction_detection:
  current_uav_height: 0.0
  min_dis_new_junction: 30.0
  min_detections_in_area: 20
  square_size: 15

lantern_detection:
  min_distance: 30.0
  min_detections: 20
  min_yellow_points: 200
